version: '3'

networks:
  graylog_net:

services:
  mongo:
    image: mongo:3
    networks:
      - graylog_net
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - graylog_net
    deploy:
      resources:
        limits:
          memory: 2048M
  graylog:
    image: graylog/graylog:3.0
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:39000/
    depends_on:
      - mongo
      - elasticsearch
    networks:
      - graylog_net
    ports:
      # Graylog web interface and REST API
      - 39000:9000
      # Syslog TCP
      - 3514:1514
      # Syslog UDP
      - 3514:1514/udp
      # GELF TCP
      - 32201:12201
      # GELF UDP
      - 32201:12201/udp
